[package]
name = "rokumon"
version = "0.1.0"
authors = ["Ivan Veselov <veselov@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
rand = "0.7"
itertools = "0.9"
failure = "0.1"
rubot = "0.2"
